# log frequency
val_check_interval: 1
progress_bar_refresh_rate: 1

wandb:
  # name: ${expname}
  project: diffcsp_symmetry
  entity: symmetry_group
  name: ${runname}
  log_model: True
  mode: 'online'
  group: ${expname}
  save_dir: ${wandb_dir}

wandb_watch:
  log: 'all'
  log_freq: 500

lr_monitor:
  logging_interval: "step"
  log_momentum: False