_target_: diffcsp.pl_modules.discrete_diffusion_w_site_symm.CSPDiffusion
time_dim: 256
latent_dim: 0
cost_coord: 1.
cost_lattice: 1.
cost_type: 1.
cost_symm: 10.
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
timesteps: 1000
ip: true
use_ks: false
use_gt_frac_coords: false
use_site_symm: false

defaults:
  - decoder: cspnet
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped